
github:
  description: Dashboard for Apache APISIX
  homepage: https://apisix.apache.org/
  labels:
    - dashboard
    - api
    - api-management
    - apisix
    - devops

  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false

  protected_branches:
    master:
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 2

  notifications:
    commits: notifications@apisix.apache.org
    issues: notifications@apisix.apache.org
    pullrequests: notifications@apisix.apache.org
